### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by jakubvojacek** [mallgroup/roadrunner#11]
Hello

do you have stats comparing roadrunner vs fpm? I have deployed it on one installation and the results are not as good as I hoped for them to be. 

I got haproxy balaning the traffic in between fpm and roadrunner and according to the prometheus metric `haproxy_server_response_time_average_seconds` the difference is within 0-1 milliseconds (average response time for both is around 20 to 25ms)

When manually trying some `time curl xxx` then the roadrunner seems faster by around 10% but overall, according to the haproxy stats, the results are pretty much the same.

Do you have some stats how much the performance has improved? Or how to measure it? I hope I can trust the haproxy stats..

Hope you dont mind me asking, I know its not really related to nette integration of roadrunner but rather roadrunner in general

Thanks
Jakub

**Comment by bckp** [comment]
Well. we have some stats done by ourselfs, but not agaist FPM. We compared Apache vs Roadrunner, there is speed improvement about 20-30%.

We mostly benefit from time to prepare (eg we have time to load data into caches before RR receive first request and keep it in memory thru all requests) and time after response is send, to write some stats, caches etc... So we minimalize time-to-response and ofload non-essential data to request after response is send.

But nette is not set to run in roadrunner by design, so i guess it will need some tweaks to run properly (eg: share caches between requests, not flush all stuff etc).

Radovan

**Comment by jakubvojacek** [comment]
it was a actually problem with one model doing local caching which was working perfectly in single request in FPM (`if property === null ? getSomething : something`). 

But the `something` was not behaving correctly and we re-calculated the whole stuff instead of using redis cache. 

After fixing this, we're now at average times of 9-10ms from 20ms that we had previously on FPM. And CPU is around 50% less used. That's a good upgrade!

Thanks again for the support!
